from __future__ import annotations

from .prompting.builders import (
  build_conversation_response_prompt,
  build_document_artifact_prompt,
  build_domain_research_prompt,
  build_dynamic_agent_definition_prompt,
  build_intent_analysis_prompt,
  build_minimal_simple_code_prompt,
  build_routing_prompt,
  build_routing_repair_prompt,
  build_scoped_update_patch_prompt,
  build_simple_code_prompt,
  build_task_decomposition_prompt,
  build_update_analysis_prompt,
  build_website_prompt,
  build_workflow_planning_prompt,
)
from .prompting.contracts import (
  CONVERSATION_RESPONSE_CONTRACT,
  DOCUMENT_ARTIFACT_OUTPUT_CONTRACT,
  DOMAIN_RESEARCH_RESPONSE_CONTRACT,
  DYNAMIC_AGENT_DEFINITION_CONTRACT,
  DYNAMIC_TASK_DECOMPOSITION_CONTRACT,
  DYNAMIC_WORKFLOW_PLAN_CONTRACT,
  ROUTING_RESPONSE_CONTRACT,
  SCOPED_UPDATE_PATCH_CONTRACT,
  SIMPLE_CODE_ARTIFACT_OUTPUT_CONTRACT,
  UPDATE_ANALYSIS_CONTRACT,
  WEBSITE_ARTIFACT_OUTPUT_CONTRACT,
)
from .prompting.instructions import (
  CONVERSATION_SYSTEM_INSTRUCTION,
  DOCUMENT_ARTIFACT_SYSTEM_INSTRUCTION,
  ENTERPRISE_AI_NATIVE_BLUEPRINT,
  ROUTING_SYSTEM_INSTRUCTION,
  SIMPLE_CODE_SYSTEM_INSTRUCTION,
  SYSTEM_INSTRUCTION,
  build_gemini_system_instruction,
)

__all__ = [
  "CONVERSATION_RESPONSE_CONTRACT",
  "DOCUMENT_ARTIFACT_OUTPUT_CONTRACT",
  "CONVERSATION_SYSTEM_INSTRUCTION",
  "DOCUMENT_ARTIFACT_SYSTEM_INSTRUCTION",
  "DOMAIN_RESEARCH_RESPONSE_CONTRACT",
  "DYNAMIC_AGENT_DEFINITION_CONTRACT",
  "DYNAMIC_TASK_DECOMPOSITION_CONTRACT",
  "DYNAMIC_WORKFLOW_PLAN_CONTRACT",
  "ENTERPRISE_AI_NATIVE_BLUEPRINT",
  "ROUTING_RESPONSE_CONTRACT",
  "ROUTING_SYSTEM_INSTRUCTION",
  "SCOPED_UPDATE_PATCH_CONTRACT",
  "SIMPLE_CODE_ARTIFACT_OUTPUT_CONTRACT",
  "SIMPLE_CODE_SYSTEM_INSTRUCTION",
  "SYSTEM_INSTRUCTION",
  "UPDATE_ANALYSIS_CONTRACT",
  "WEBSITE_ARTIFACT_OUTPUT_CONTRACT",
  "build_intent_analysis_prompt",
  "build_minimal_simple_code_prompt",
  "build_update_analysis_prompt",
  "build_scoped_update_patch_prompt",
  "build_simple_code_prompt",
  "build_task_decomposition_prompt",
  "build_dynamic_agent_definition_prompt",
  "build_workflow_planning_prompt",
  "build_domain_research_prompt",
  "build_routing_prompt",
  "build_routing_repair_prompt",
  "build_conversation_response_prompt",
  "build_document_artifact_prompt",
  "build_website_prompt",
  "build_gemini_system_instruction",
]
